version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sdk"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/sample-app/anonymous-voting"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
